### ISSUE TITLE
Create a proper NPC

### ISSUE THREAD

**Issue by CMarth** [FourCornerEarth/TimeCubeousGame#6]
Add a proper NPC. you should be able to:
-- talk to it
-- have it talk instantly
-- allow it to both move in a set course and stay still

Also
a sign or chest that will bring up a textbox when interacted with

**Comment by CMarth** [comment]
missing motion for npc as well as for it to give you an item
npc can now talk to you when collided with

**Comment by techiecheckie** [comment]
This is tooooootally done.
