### ISSUE TITLE
Create a base for the Inventory system

### ISSUE THREAD

**Issue by CMarth** [FourCornerEarth/TimeCubeousGame#7]
Open and view inventory in your menu. Make an NPC give MC an item for testing to add to that inventory and testing to get an item from an npc

**Comment by techiecheckie** [comment]
Inventory menu stuff is done, with add and remove functions done. Remove needs to be made reactive.

**Comment by techiecheckie** [comment]
Oki dokes. Base for inventory is a go! We may want to refactor a little bit, that'll be a new issue. :)
